sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sonarcloud:
    organization: "metamagic" # the key of the org you chose at step #3
    token:
      secure: c52d859733b46f36e4e3d812f24f416b8fb6b9a0 # encrypted value of your token   
 
language: node_js
node_js:
  - "8"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --global gulp --save
  - gem install sass
  - git fetch --unshallow
  - gulp -v

            
script: 
  - gulp test
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner ; fi
  - cd src/styles/ && sh sasstocss.sh
  - cd ../../ && pwd && gulp build --max_old_space_size=4096
  - cd dist && npm pack
  - mv amexio-ng-extensions-*.tgz amexio-ng-extensions.tgz
  
after_success: 
  - cd ../
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git clone https://github.com/meta-magic/amexio-ios.git -b v5.15 ; fi 
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cd amexio-ios ; fi 
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cp -rf ../dist/amexio-ng-extensions.tgz . ; fi 
 # - cp -rf ../src/styles/css/*  themes/
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git add amexio-ng-extensions.tgz ; fi 
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git commit -m "date" ; fi 
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push "https://deepali-arvind:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" HEAD:v5.15 ; fi 
  - gulp coveralls 
  - codecov

cache:
  yarn: true
  
